In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
a = arange(5)
b = ones(5)
a

array([0, 1, 2, 3, 4])

In [3]:
b

array([ 1.,  1.,  1.,  1.,  1.])

In [4]:
a - b * 3

array([-3., -2., -1.,  0.,  1.])

In [5]:
sorted(a - b * 3)

[-3.0, -2.0, -1.0, 0.0, 1.0]