# Multidimensional Arrays in NumPy

NumPy arrays are rectangles in as many dimensions as you need.

In [1]:
import numpy as np

In [4]:
M = np.arange(24).reshape([2,4,3])
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

``M`` is a 3-dimensional "data cube" of size 2x4x3. We can access individual elements by subscripting:

In [7]:
np.arange(100)[80:85]

array([80, 81, 82, 83, 84])

In [9]:
M[:, 1:, 0 : 2]

array([[[ 3,  4],
        [ 6,  7],
        [ 9, 10]],

       [[15, 16],
        [18, 19],
        [21, 22]]])

In [8]:
M[1,1,1]

16

Arithmetic operators work element-by-element for same-shape arrays.

You can also add/multiply/etc a single value that will be applied to every element.

In [10]:
M + M / 2.0

array([[[ 0. ,  1.5,  3. ],
        [ 4.5,  6. ,  7.5],
        [ 9. , 10.5, 12. ],
        [13.5, 15. , 16.5]],

       [[18. , 19.5, 21. ],
        [22.5, 24. , 25.5],
        [27. , 28.5, 30. ],
        [31.5, 33. , 34.5]]])

In [13]:
M[:,0,1].reshape((1,2,1))

array([[[ 1],
        [13]]])

In [15]:
M[:,0,1].reshape((2,1,1)) + M

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

## Array slicing

The subscript index notation can also be used to retrieve "slices" of a larger array instead of single values. Use a colon ":" character to specify a range or on its own as a placeholder to fetch an entire dimension.

In [16]:
M[1,:,:]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
s = M[1,:,0:2]
s

array([[12, 13],
       [15, 16],
       [18, 19],
       [21, 22]])

Array slices can be used as standalone arrays. But watch out! They are references into your original array, and changing them can change the original.

In [18]:
s * 10

array([[120, 130],
       [150, 160],
       [180, 190],
       [210, 220]])

In [19]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [20]:
s[:] = 0
s

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [21]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

Use the ``.copy()`` method to avoid this behavior:

In [22]:
S = M[0,:,:].copy()

In [23]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

In [24]:
S

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
S[:] = 10

In [26]:
S

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [27]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

In [28]:
M == 5

array([[[False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [29]:
M % 2 == 0

array([[[ True, False,  True],
        [False,  True, False],
        [ True, False,  True],
        [False,  True, False]],

       [[ True,  True,  True],
        [ True,  True, False],
        [ True,  True,  True],
        [ True,  True, False]]])

In [30]:
evens = M[M % 2 == 0]

In [31]:
evens

array([ 0,  2,  4,  6,  8, 10,  0,  0, 14,  0,  0,  0,  0, 20,  0,  0])

In [32]:
evens = evens ** 2 + 10

In [33]:
evens

array([ 10,  14,  26,  46,  74, 110,  10,  10, 206,  10,  10,  10,  10,
       410,  10,  10])

In [34]:
M

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0, 14],
        [ 0,  0, 17],
        [ 0,  0, 20],
        [ 0,  0, 23]]])

In [35]:
M[M % 2 == 0] = evens

In [36]:
M

array([[[ 10,   1,  14],
        [  3,  26,   5],
        [ 46,   7,  74],
        [  9, 110,  11]],

       [[ 10,  10, 206],
        [ 10,  10,  17],
        [ 10,  10, 410],
        [ 10,  10,  23]]])